# MNIST分类

In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/",one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [2]:
tf.reset_default_graph()
#定义占位符
x = tf.placeholder(tf.float32,[None,784]) #28*28=784
y = tf.placeholder(tf.float32,[None,10]) #0~9,None表示输入任意数量的数据

In [3]:
#定义学习参数
W = tf.Variable(tf.random_normal([784,10])) #权重
b = tf.Variable(tf.zeros([10])) #偏置

In [4]:
#定义输出节点,正向传输
pred = tf.nn.softmax(tf.matmul(x,W) + b) #pred = W*x + b

In [5]:
#定义方向传播结构
#损失函数
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(pred),reduction_indices=1))
#学习率
learning_rate = 0.01
#优化器--这里使用梯度下降
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

## 训练、保存模型

In [6]:
#迭代次数
training_epochs = 200
#batch_size 每次训练取的数据量
batch_size = 100
#中间状态打印间隔
display_step = 1 

#模型保存路径
saver = tf.train.Saver()
model_path = "log/521model.ckpt"

#启动Session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer()) #Initializing OP
    
    #启动循环开始训练
    for epoch in range(training_epochs):
        avg_cost = 0.
        total_batch = int(mnist.train.num_examples / batch_size)
        #循环所有数据集
        for i in range(total_batch):
            batch_xs,batch_ys = mnist.train.next_batch(batch_size)
            #运行优化器
            _, c = sess.run([optimizer,cost],feed_dict={x:batch_xs,y:batch_ys})
            #平均损失
            avg_cost += c /total_batch
        #显示信息
        if (epoch+1) % display_step == 0:
            print("Epoch:",'%04d' % (epoch+1),"cost=","{:.9f}".format(avg_cost))
    print("Finished!")
    
    #测试模型
    correct_prediction = tf.equal(tf.argmax(pred,1),tf.argmax(y,1))
    #计算精确率
    accuracy = f=tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
    print("Accuracy:",accuracy.eval({x:mnist.test.images,y:mnist.test.labels}))
    
    #保存模型
    save_path = saver.save(sess,model_path)
    print("Model saved in file: %s" % save_path)
    
#测试模型    
import pylab
print ("Starting restore Model and the second Session...")
with tf.Session() as sess:
    #初始化变量
    sess.run(tf.global_variables_initializer())
    #恢复模型变量
    saver.restore(sess,model_path)
    
    #测试模型
    correct_predict = tf.equal(tf.argmax(pred,1),tf.argmax(y,1))
    #计算精确度
    accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
    print("Accuracy:",accuracy.eval({x:mnist.test.images,y:mnist.test.labels}))
    
    output = tf.argmax(pred,1)
    batch_xs,batch_ys = mnist.train.next_batch(4)
    outputval,predv = sess.run([output,pred],feed_dict={x:batch_xs,y:batch_ys})
    print(outputval,predv,batch_ys)
    
    im = batch_xs[0]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()
    
    im = batch_xs[1]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()
    
    im = batch_xs[2]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()
    
    im = batch_xs[3]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()

Epoch: 0001 cost= 8.976913220
Epoch: 0002 cost= 4.733122895
Epoch: 0003 cost= 3.255746334
Epoch: 0004 cost= 2.553567848
Epoch: 0005 cost= 2.142943900
Epoch: 0006 cost= 1.874906544
Epoch: 0007 cost= 1.687199714
Epoch: 0008 cost= 1.548528033
Epoch: 0009 cost= 1.441754161
Epoch: 0010 cost= 1.356811014
Epoch: 0011 cost= 1.287214426
Epoch: 0012 cost= 1.228989819
Epoch: 0013 cost= 1.179359489
Epoch: 0014 cost= 1.136352248
Epoch: 0015 cost= 1.098950819
Epoch: 0016 cost= 1.065595591
Epoch: 0017 cost= 1.035973967
Epoch: 0018 cost= 1.009133914
Epoch: 0019 cost= 0.984901657
Epoch: 0020 cost= 0.962814927
Epoch: 0021 cost= 0.942425323
Epoch: 0022 cost= 0.923716131
Epoch: 0023 cost= 0.906294772
Epoch: 0024 cost= 0.890110382
Epoch: 0025 cost= 0.875045527
Epoch: 0026 cost= 0.860943490
Epoch: 0027 cost= 0.847613270
Epoch: 0028 cost= 0.835109133
Epoch: 0029 cost= 0.823332681
Epoch: 0030 cost= 0.812061847
Epoch: 0031 cost= 0.801490700
Epoch: 0032 cost= 0.791373967
Epoch: 0033 cost= 0.781719713
Epoch: 003

## 读取模型

In [7]:
import pylab
print ("Starting restore Model and the second Session...")
with tf.Session() as sess:
    #初始化变量
    sess.run(tf.global_variables_initializer())
    #恢复模型变量
    saver.restore(sess,model_path)
    
    #测试模型
    correct_predict = tf.equal(tf.argmax(pred,1),tf.argmax(y,1))
    #计算精确度
    accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))
    print("Accuracy:",accuracy.eval({x:mnist.test.images,y:mnist.test.labels}))
    
    output = tf.argmax(pred,1)
    batch_xs,batch_ys = mnist.train.next_batch(4)
    outputval,predv = sess.run([output,pred],feed_dict={x:batch_xs,y:batch_ys})
    print(outputval,predv,batch_ys)
    
    im = batch_xs[0]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()
    
    im = batch_xs[1]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()
    
    im = batch_xs[2]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()
    
    im = batch_xs[3]
    im = im.reshape(-1,28)
    pylab.imshow(im)
    pylab.show()

Starting restore Model and the second Session...
INFO:tensorflow:Restoring parameters from log/521model.ckpt
Accuracy: 0.8943
[6 6 9 6] [[  3.24059979e-09   8.71780074e-17   1.35509854e-05   2.12521805e-08
    2.51669633e-07   4.37270819e-06   9.99981761e-01   1.07654741e-09
    5.09777323e-08   7.27295613e-10]
 [  3.24516217e-12   4.93763504e-13   2.05972086e-07   1.02106261e-10
    8.45428616e-08   5.16235366e-09   9.99999762e-01   6.85560278e-14
    4.43251587e-08   5.08301456e-10]
 [  1.08700033e-06   1.28877398e-09   6.50018865e-06   3.32755561e-04
    1.17122683e-04   2.78560221e-02   2.33683204e-06   1.67513736e-06
    1.87694021e-02   9.52913046e-01]
 [  1.73523929e-09   7.43960481e-05   1.52927334e-03   1.10765100e-02
    4.67787868e-05   4.48837643e-04   9.64665413e-01   1.86740112e-09
    2.09163893e-02   1.24238257e-03]] [[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 