In [35]:
import tensorflow as tf
import numpy as np

In [36]:
tf.reset_default_graph()

In [37]:
#输入数据
X = np.random.randn(2,4,5)

In [38]:
#第二个样本长度为3
X[1,1:] = 0
seq_lengths = [4,1]

In [39]:
#分别建立一个LSTM 和GRU 的cell，比较输出状态
cell = tf.contrib.rnn.BasicLSTMCell(num_units=3,state_is_tuple=True)
gru = tf.contrib.rnn.GRUCell(3)

In [40]:
#如果没有initial_state，必须指定a dtype
outputs,last_states = tf.nn.dynamic_rnn(cell,X,sequence_length=seq_lengths,dtype=tf.float64)
gruoutputs,grulast_states = tf.nn.dynamic_rnn(gru,X,sequence_length=seq_lengths,dtype=tf.float64)
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
result,sta,gruout,grusta = sess.run([outputs,last_states,gruoutputs,grulast_states])
sess.close()

/home/mkd/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py:1711: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [41]:
print("全序列:\n",result[0])
print("短序列:\n",result[1])
print('LSTM的状态：',len(sta),'\n',sta[1])
print('GRU的短序列：\n',gruout[1])
print('GRU的短序列：',len(grusta),'\n',grusta[1])

全序列:
 [[ 0.02058001 -0.02315916 -0.25604274]
 [-0.00570115 -0.20019696 -0.10043848]
 [-0.16344654 -0.22001124  0.06003174]
 [-0.35928287  0.08392175  0.1320911 ]]
短序列:
 [[0.00278191 0.02893197 0.11737706]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
LSTM的状态： 2 
 [[-0.35928287  0.08392175  0.1320911 ]
 [ 0.00278191  0.02893197  0.11737706]]
GRU的短序列：
 [[-0.03508312 -0.33684871 -0.40246296]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
GRU的短序列： 2 
 [-0.03508312 -0.33684871 -0.40246296]


In [43]:
sta

LSTMStateTuple(c=array([[-0.65942754,  0.11060666,  0.30867179],
       [ 0.014333  ,  0.05643109,  0.35662615]]), h=array([[-0.35928287,  0.08392175,  0.1320911 ],
       [ 0.00278191,  0.02893197,  0.11737706]]))

In [44]:
grusta

array([[ 0.28298832,  0.11345035,  0.16811909],
       [-0.03508312, -0.33684871, -0.40246296]])